export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "mailinator.com","guerrillamail.com","guerrillamail.org","guerrillamail.net",
  "guerrillamail.de","guerrillamail.info","guerrillamail.biz","spam4.me",
  "trashmail.com","trashmail.me","trashmail.net","trashmail.org","trashmail.at",
  "trashmail.io","throwam.com","throwam.net","yopmail.com","yopmail.fr",
  "yopmail.net","cool.fr.nf","jetable.fr.nf","nospam.ze.tc","nomail.xl.cx",
  "mega.zik.dj","speed.1s.fr","courriel.fr.nf","moncourrier.fr.nf",
  "monemail.fr.nf","monmail.fr.nf","fakeinbox.com","dispostable.com",
  "mailnull.com","maildrop.cc","mailnesia.com","spamgourmet.com",
  "tempmail.com","tempmail.net","tempmail.org","temp-mail.org","temp-mail.io",
  "getairmail.com","filzmail.com","throwam.com","spamex.com",
  "mailexpire.com","deadaddress.com","spamfree24.org","spam.la",
  "crap.to","spamdecoy.net","kasmail.com","mailscrap.com","spamhole.com",
  "mailzilla.org","guerillamail.com","throwaway.email","wegwerfmail.de",
  "wegwerfmail.net","wegwerfmail.org","spamify.com","binkmail.com","bo.lt",
  "clrmail.com","dacoolest.com","discard.email","discardmail.com",
  "discardmail.de","dontreg.com","dontsendmespam.de","drdrb.com",
  "dudmail.com","fakedemail.com","fakemailz.com","filzmail.de",
  "getnada.com","getonemail.com","gotmail.net","gotmail.org","guerrillamailblock.com",
  "haltospam.com","inboxalias.com","jourrapide.com","kurzepost.de",
  "lifebyfood.com","lol.ovpn.to","lookugly.com","lortemail.dk",
  "mailandftp.com","mailbidon.com","mailbiz.biz","mailblocks.com",
  "mailboxt.com","mailchop.com","mailcker.com","maildu.de","maileater.com",
  "maileme101.com","mailforspam.com","mailfreeonline.com","mailguard.me",
  "mailimate.com","mailin8r.com","mailinater.com","mailme.ir","mailme.lv",
  "mailmetrash.com","mailmoat.com","mailnew.com","mailnew.org","mailnull.com",
  "mailrock.biz","mailscrap.com","mailshell.com","mailsiphon.com","mailslite.com",
  "mailspark.net","mailtemp.info","mailtome.de","mailtothis.com","mailw.info",
  "mailzilla.com","migmail.com","migmail.net","migumail.com","mox.pp.ua",
  "mt2009.com","mx0.wwwnew.eu","mytrashmail.com","neverbox.com","noclickemail.com",
  "nogmailspam.info","nospamfor.us","nospamthanks.info","notmailinator.com",
  "null.net","objectmail.com","obobbo.com","odnorazovoe.ru","oneoffmail.com",
  "onewaymail.com","otherinbox.com","owlpic.com","pookmail.com","privy-mail.com",
  "privy-mail.de","privymail.de","proxymail.eu","rcpt.at","recode.me",
  "recursor.net","regbypass.comsafe-mail.net","s0ny.net","safetypost.de",
  "sandelf.de","sharedmailbox.org","sharklasers.com","shieldemail.com",
  "shiftmail.com","shitmail.me","skeefmail.com","slopsbox.com","smellfear.com",
  "smwg.info","sneakemail.com","sneakmail.de","sofimail.com","sogetthis.com",
  "sofort-mail.de","spam.su","spamavert.com","spambob.com","spambob.net",
  "spambob.org","spambog.com","spambog.de","spambog.ru","spambox.me",
  "spambox.us","spamcannon.com","spamcannon.net","spamcero.com","spamcon.org",
  "spamcorptastic.com","spamcowboy.com","spamcowboy.net","spamcowboy.org",
  "spamday.com","spamdog.de","spameater.com","spameater.org","spamelot.net",
  "spamfree.eu","spamgrap.de","spamhereplease.com","spamify.com",
  "spaminator.de","spamkill.info","spaml.com","spaml.de","spammotel.com",
  "spamobox.com","spamoff.de","spamspot.com","spamthis.co.uk","spamtroll.net",
  "supergreatmail.com","supermailer.jp","suremail.info","tempalias.com",
  "tempe-mail.com","tempemail.co.za","tempemail.com","tempemail.net",
  "tempinbox.co.uk","tempinbox.com","temporary-email.com","temporaryemail.net",
  "temporaryforwarding.com","temporaryinbox.com","tempr.email","tempsky.com",
  "thanksnospam.info","thisisnotmyrealemail.com","throwam.com","tilien.com",
  "tmailinator.com","trashdevil.com","trashdevil.de","trashemail.de",
  "trashimail.com","trayna.com","trbvm.com","trbvn.com","trialmail.de",
  "trickmail.net","turual.com","twinmail.de","tyldd.com","uggsrock.com",
  "uroid.com","valemail.net","venompen.com","veryrealemail.com","viditag.com",
  "viewcastmedia.net","viewcastmedia.org","wh4f.org","whyspam.me","willselfdestruct.com",
  "wuzupmail.net","xagloo.com","xemaps.com","xents.com","xmail999.com","xmaily.com",
  "xoxy.net","xpilot.net","xsmail.com","xwaretech.com","yaboo.com","yep.it",
  "yogamaven.com","yopmail.gq","youmail.ga","za.com","zippymail.info",
  "zoemail.org","zolkmand.com","spamgourmet.net","spamgourmet.org",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return true;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
